# Generated by Django 4.0.5 on 2022-06-23 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField()),
                ('homework_details', models.TextField()),
                ('due_date', models.DateField()),
                ('Grade', models.CharField(max_length=5)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.student')),
            ],
        ),
    ]
